#' @name gl.collapse
#' @title Collapses a distance matrix by amalgamating populations with pairwise
#'  fixed difference count less than or equal to a threshold
#' @family fixed difference analysis
#' @description
#' This function takes the list of matrices generated by gl.fixed.diff() and
#' amalgamates populations with a fixed difference count less than or equal
#' to a specified threshold (\code{tpop}).
#'
#' The function then applies the new population assignments to the genlight
#' object and recalculates the fixed difference and associated matrices.
#'
#' @details
#' Populations are grouped transitively: A and C are amalgamated when A-B
#' and B-C each have \code{tpop} or fewer fixed differences, even if A-C has
#' more. Each group is labelled with the first population name in
#' alphabetical order followed by "+". Population pairs with no fixed
#' difference count (NA, e.g. no loci in common) are not amalgamated.
#'
#' \code{tloc} must be the value used in the call to gl.fixed.diff() that
#' produced \code{fd}; the function checks this by recomputing the fixed
#' differences and stops if they differ.
#'
#' If no populations are amalgamated, \code{fd} is returned unchanged. If all
#' populations fall into one group, the returned genlight has one population
#' and the matrices are 1 x 1.
#'
#' @param fd Name of the list of matrices produced by gl.fixed.diff()
#' [required].
#' @param tloc Threshold defining a fixed difference (e.g. 0.05 implies 95:5 vs
#'  5:95 is fixed); must match the value used in gl.fixed.diff() [default 0].
#' @param tpop Threshold number of fixed differences above which populations
#' will not be amalgamated [default 0].
#' @param pb If TRUE, show a progress bar on time consuming loops
#' [default FALSE].
#' @param verbose Verbosity: 0, silent or fatal errors; 1, begin and end; 2,
#' progress log; 3, progress and results summary; 5, full report
#' [default 2 or as specified using gl.set.verbosity]
#' @return A list of class 'fd' containing the new genlight object and square
#' matrices:
#' \enumerate{
#'  \item $gl -- the new genlight object with populations collapsed;
#'  \item $fd -- raw fixed differences;
#'  \item $pcfd -- percent fixed differences;
#'  \item $nobs -- mean no. of individuals used in each comparison;
#'  \item $nloc -- total number of loci used in each comparison;
#'  \item $expfpos -- NA's, populated by gl.fixed.diff [by simulation];
#'  \item $sdfpos -- NA's, populated by gl.fixed.diff [by simulation];
#'  \item $pval -- NA's, populated by gl.fixed.diff [by simulation].
#'         }
#' @importFrom methods show
#' @export
#' @author Author(s): Arthur Georges. Custodian: Arthur Georges -- Post to
#' \url{https://groups.google.com/d/forum/dartr}
#' @examples
#'  \donttest{
#' fd <- gl.fixed.diff(testset.gl, tloc = 0.05)
#' fd
#' fd2 <- gl.collapse(fd, tpop = 1, tloc = 0.05)
#' fd2
#' fd3 <- gl.collapse(fd2, tpop = 1, tloc = 0.05)
#' fd3
#' }
#'  fd <- gl.fixed.diff(testset.gl, tloc = 0)
#'  fd2 <- gl.collapse(fd)

gl.collapse <- function(fd,
                        tpop = 0,
                        tloc = 0,
                        pb = FALSE,
                        verbose = NULL) {
    # SET VERBOSITY
    verbose <- gl.check.verbosity(verbose)

    # FLAG SCRIPT START
    funname <- match.call()[[1]]
    utils.flag.start(func = funname, verbose = verbose)

    # CHECK DATATYPE
    datatype <-
        utils.check.datatype(fd, accept = "fd", verbose = verbose)

    # FUNCTION SPECIFIC ERROR CHECKING

    if (!is.numeric(tloc) || length(tloc) != 1 || is.na(tloc) ||
        tloc > 0.5 || tloc < 0) {
        stop(error(
            "Fatal Error: Parameter tloc should be one number in the range 0",
            "to 0.5\n"
        ))
    }

    if (!is.numeric(tpop) || length(tpop) != 1 || is.na(tpop) || tpop < 0) {
        stop(error(
            "Fatal Error: Parameter tpop should be one non-negative number\n"
        ))
    }

    # The grouping uses fd$fd, computed by gl.fixed.diff() with its own tloc,
    # while the returned matrices are recomputed with this tloc; the two must
    # be the same definition of a fixed difference.
    fd_check <- gl.fixed.diff(fd$gl, tloc = tloc, pb = pb, verbose = 0)
    if (!isTRUE(all.equal(as.matrix(fd_check$fd), as.matrix(fd$fd),
                          check.attributes = FALSE))) {
        stop(error(paste0(
            "Fatal Error: the fixed differences in 'fd' do not match those ",
            "computed with tloc = ", tloc, ". Set tloc to the value used in ",
            "gl.fixed.diff().\n"
        )))
    }

    # DO THE JOB

    if (verbose >= 2) {
        if (tloc > 0) {
            cat(report(
                "  Comparing populations for fixed differences with tolerance",
                tloc, "\n"
            ))
        }
        if (tloc == 0) {
            cat(report(
                "  Comparing populations for absolute fixed differences\n"
            ))
        }
        if (tpop == 1) {
            cat(report(
                "  Amalgamating populations with corroborated fixed",
                "differences, tpop =", tpop, "\n"
            ))
        }
        if (tpop > 1) {
            cat(report(
                "  Amalgamating populations with fixed differences <=",
                tpop, "\n"
            ))
        }
        if (tpop == 0) {
            cat(report(
                "  Amalgamating populations with zero fixed differences\n"
            ))
        }
    }

    # Convert fd$fd from a distance matrix to a square matrix
    mat <- as.matrix(fd$fd)
    pops <- rownames(mat)

    if (anyNA(mat) && verbose >= 1) {
        cat(warn(
            "  Warning: some population pairs have no fixed difference count",
            "(NA) and are not amalgamated\n"
        ))
    }

    zero.list <- utils.collapse.groups(mat, tpop)

    # Print out the results of the aggregations
    if (verbose >= 3) {
        cat(report("  Initial populations:", paste(pops, collapse = ", "),
                   "\n"))
    }

    # No amalgamation: return the input unchanged
    if (length(zero.list) == length(pops)) {
        if (verbose >= 2) {
            cat(report("  No further amalgamation of populations at fd <=",
                       tpop, "\n"))
        }
        if (verbose >= 1) {
            cat(report("Completed:", funname, "\n"))
        }
        return(fd)
    }

    x <- fd$gl
    for (i in seq_along(zero.list)) {
        if (length(zero.list[[i]]) == 1) next
        # Create a group label
        replacement <- paste0(zero.list[[i]][1], "+")
        if (verbose >= 3) {
            cat(report("  Group", replacement, ":",
                       paste(zero.list[[i]], collapse = ", "), "\n"))
        }
        # Amalgamate the populations
        x <-
            gl.merge.pop(x,
                         old = zero.list[[i]],
                         new = replacement,
                         verbose = 0)
    }

    if (nPop(x) == 1) {
        # All populations in one group: gl.fixed.diff() needs two populations
        if (verbose >= 1) {
            cat(report("  All populations amalgamated into one group,",
                       popNames(x), "\n"))
        }
        one <- matrix(0, 1, 1, dimnames = list(popNames(x), popNames(x)))
        na1 <- one
        na1[1, 1] <- NA
        l <- list(
            gl = x,
            fd = stats::as.dist(one),
            pcfd = stats::as.dist(one),
            nobs = na1,
            nloc = na1,
            expfpos = na1,
            sdfpos = na1,
            pval = na1
        )
        class(l) <- "fd"
    } else {
        # Recalculate matrices
        fd2 <- gl.fixed.diff(x,
                             tloc = tloc,
                             pb = pb,
                             verbose = 0)

        # Display the fd matrix
        if (verbose >= 5) {
            cat(report("  Raw fixed difference matrix\n"))
            print(fd2$fd)
        }
        if (verbose >= 3) {
            cat(report("  Sample sizes\n"))
            print(table(pop(fd2$gl)))
        }

        # Create the list for output
        l <-
            list(
                gl = fd2$gl,
                fd = fd2$fd,
                pcfd = fd2$pcfd,
                nobs = fd2$nobs,
                nloc = fd2$nloc,
                expfpos = fd2$expfpos,
                sdfpos = fd2$sdfpos,
                pval = fd2$pval
            )
        class(l) <- "fd"
    }

    # Explanatory bumpf
    if (verbose >= 3) {
        if (pb) {
            cat("\n")
        }
        cat(report(
            "  Returning a list of class 'fd' containing the new genlight",
            "object and square matrices, as follows:\n",
            "         [[1]] $gl -- genlight object with populations collapsed;\n",
            "         [[2]] $fd -- raw fixed differences;\n",
            "         [[3]] $pcfd -- percent fixed differences;\n",
            "         [[4]] $nobs -- mean no. of individuals used in each comparison;\n",
            "         [[5]] $nloc -- total number of loci used in each comparison;\n",
            "         [[6]] $expfpos -- NAs, populated by gl.fixed.diff [by simulation];\n",
            "         [[7]] $sdfpos -- NAs, populated by gl.fixed.diff [by simulation];\n",
            "         [[8]] $pval -- NAs, populated by gl.fixed.diff [by simulation].\n"
        ))
    }

    # FLAG SCRIPT END

    if (verbose > 0) {
        cat(report("Completed:", funname, "\n"))
    }

    return(l)
}
